import { ImageResponse } from "next/og";
import { auth } from "@/lib/auth/server";
import { getTogetherStoryData } from "@/lib/story";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function row(label:string,value:string){return <div style={{display:"flex",justifyContent:"space-between",gap:18,padding:"16px 0",borderBottom:"1px solid rgba(255,255,255,.08)",fontSize:27}}><div style={{display:"flex",color:"#a9c4b4"}}>{label}</div><div style={{display:"flex",fontWeight:800}}>{value}</div></div>}

export async function GET(){
  const {data:session}=await auth.getSession();
  if(!session?.user)return new Response("Unauthorized",{status:401});
  const story=await getTogetherStoryData(session.user.id);

  if(!story.hasPartner||!story.partner){
    return new ImageResponse(<div style={{width:1080,height:1920,display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"72px 68px",background:"radial-gradient(circle at top right,#1d5a39 0%,#0f2419 35%,#07130e 100%)",color:"#f5fff8",fontFamily:"Arial, sans-serif"}}><div style={{display:"flex",flexDirection:"column",gap:24}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{display:"flex",fontSize:36,fontWeight:800,color:"#c8ffd8"}}>PairFuel</div><div style={{display:"flex",fontSize:24,padding:"10px 18px",border:"1px solid rgba(255,255,255,.16)",borderRadius:999,color:"#c8ffd8"}}>Together Story</div></div><div style={{display:"flex",fontSize:80,fontWeight:900,lineHeight:1}}>Better Together 💑</div><div style={{display:"flex",fontSize:32,color:"#a9c4b4"}}>{story.sharedMessage}</div></div><div style={{display:"flex",fontSize:42,padding:"30px",borderRadius:28,background:"rgba(255,255,255,.07)",border:"1px solid rgba(255,255,255,.10)"}}>Connect your partner first to unlock couple stats ✨</div><div style={{display:"flex",justifyContent:"space-between",fontSize:24,color:"#a9c4b4"}}><div style={{display:"flex"}}>pairfuel.vercel.app</div><div style={{display:"flex"}}>© 2026 Elton Malumbot Production</div></div></div>,{width:1080,height:1920});
  }

  const p=story.partner;
  return new ImageResponse(<div style={{width:1080,height:1920,display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"64px 60px",background:"radial-gradient(circle at top right,#1d5a39 0%,#0f2419 35%,#07130e 100%)",color:"#f5fff8",fontFamily:"Arial, sans-serif"}}><div style={{display:"flex",flexDirection:"column",gap:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",fontSize:36,fontWeight:800,color:"#c8ffd8"}}>PairFuel</div><div style={{display:"flex",fontSize:24,padding:"10px 18px",border:"1px solid rgba(255,255,255,.16)",borderRadius:999,color:"#c8ffd8"}}>Together Story</div></div><div style={{display:"flex",fontSize:76,fontWeight:900,lineHeight:1}}>{story.headline}</div><div style={{display:"flex",fontSize:30,color:"#a9c4b4"}}>{story.sharedMessage}</div></div><div style={{display:"flex",gap:24}}><div style={{width:"50%",display:"flex",flexDirection:"column",padding:28,borderRadius:28,background:"rgba(255,255,255,.07)",border:"1px solid rgba(255,255,255,.10)"}}><div style={{display:"flex",fontSize:32,fontWeight:900}}>Me</div><div style={{display:"flex",fontSize:24,color:"#a9c4b4",marginBottom:16}}>{story.me.displayName}</div>{row("🍽️ Calories",`${story.me.calories} / ${story.me.calorieTarget}`)}{row("🥩 Protein",`${story.me.protein} / ${story.me.proteinTarget} g`)}{row("💧 Water",`${story.me.water} / ${story.me.waterTarget} ml`)}{row("⏳ Fasting",story.me.fastingLabel)}{row("🔥 Status",story.me.onTrack?"On Track":"Keep Going")}</div><div style={{width:"50%",display:"flex",flexDirection:"column",padding:28,borderRadius:28,background:"rgba(255,255,255,.07)",border:"1px solid rgba(255,255,255,.10)"}}><div style={{display:"flex",fontSize:32,fontWeight:900}}>Partner</div><div style={{display:"flex",fontSize:24,color:"#a9c4b4",marginBottom:16}}>{p.displayName}</div>{row("🍽️ Calories",p.shareCalories?`${p.calories} / ${p.calorieTarget}`:"Private 🔒")}{row("🥩 Protein",p.shareMacros?`${p.protein} / ${p.proteinTarget} g`:"Private 🔒")}{row("💧 Water",p.shareWater?`${p.water} / ${p.waterTarget} ml`:"Private 🔒")}{row("⏳ Fasting",p.shareFasting?(p.fastingLabel||"—"):"Private 🔒")}{row("⚖️ Weight",p.shareWeight&&p.weight!==undefined?`${p.weight} kg`:p.shareWeightChange&&p.weightChange!==undefined?`${p.weightChange>0?"+":""}${p.weightChange} kg change`:"Private 🔒")}{row("💚 Status",p.onTrack===null?"Private 🔒":p.onTrack?"On Track":"Keep Going")}</div></div><div style={{display:"flex",flexDirection:"column",gap:18}}><div style={{display:"flex",fontSize:36,fontWeight:800,color:"#c8ffd8"}}>Better habits, better together ✨</div><div style={{display:"flex",justifyContent:"space-between",fontSize:24,color:"#a9c4b4"}}><div style={{display:"flex"}}>pairfuel.vercel.app</div><div style={{display:"flex"}}>© 2026 Elton Malumbot Production</div></div></div></div>,{width:1080,height:1920});
}
