const QUOTES = [
  "Small choices, repeated daily, create a healthier life.",
  "Progress is built one balanced meal at a time.",
  "You do not need perfect days, only consistent ones.",
  "Fuel your body for the life you want to live.",
  "Healthy habits become easier every time you repeat them.",
  "Choose food that supports tomorrow's energy.",
  "Consistency beats intensity when the goal is lifelong health.",
  "A better day can begin with your very next choice.",
  "Eat with intention, move with purpose, rest without guilt.",
  "Your health is an investment you make every day.",
  "One meal never defines your journey; your pattern does.",
  "Keep showing up, even when progress feels quiet.",
  "Drink water, breathe deeply, and keep moving forward.",
  "Strong habits grow from simple promises kept to yourself.",
  "Healthy is not a punishment; it is a form of care.",
  "The goal is not less food, but better nourishment.",
  "Your body deserves patience while you build new habits.",
  "A short walk still counts. A small win still matters.",
  "Today is another chance to choose what helps you thrive.",
  "Build a lifestyle you can enjoy, not a diet you must escape.",
  "Protein, plants, water, movement, sleep: keep the basics strong.",
  "Make the healthy choice the easy choice whenever you can.",
  "You are training consistency, not chasing perfection.",
  "A calm, steady pace can take you very far.",
  "Your future energy is shaped by today's habits.",
  "Eat enough to feel strong, not just small.",
  "Good nutrition is self-respect in practical form.",
  "One glass of water is a small vote for your health.",
  "Your best routine is the one you can keep.",
  "Let progress be boring, steady, and real.",
  "Move because your body can, not because you hate it.",
  "Healthy choices add up even when the scale is quiet.",
  "A setback is information, not the end of the plan.",
  "Give your body what it needs, then give it time.",
  "You can enjoy food and still care about your goals.",
  "Balance creates results that extremes rarely sustain.",
  "Make room for joy inside a healthy lifestyle.",
  "The next healthy choice matters more than the last mistake.",
  "Sleep is part of the plan, not time away from it.",
  "Hydration is one of the simplest ways to support your body.",
  "Your routine does not need to be impressive to be effective.",
  "Choose a pace your future self can maintain.",
  "The strongest diet is the one that still feels like life.",
  "Healthy progress is measured in habits, not only kilograms.",
  "Your body changes when your daily patterns change.",
  "Do the simple things well and let time do the rest.",
  "Nourish first, restrict only when it truly serves the goal.",
  "You are allowed to take your health journey slowly.",
  "Every balanced plate is practice for the life you want.",
  "Movement can be medicine without feeling like punishment.",
  "Be proud of the days you chose consistency over impulse.",
  "You do not have to earn your food through exercise.",
  "Healthy eating works best when it still leaves room for living.",
  "Track the trend, not every tiny fluctuation.",
  "Your body responds to what you do most often.",
  "Aim for better, not flawless.",
  "A healthy routine should support your life, not control it.",
  "Keep your meals simple when motivation is low.",
  "Plan for real life, not an imaginary perfect week.",
  "Your goals deserve discipline and your body deserves kindness.",
  "Strength grows when healthy choices become automatic.",
  "Eat slowly enough to notice when your body is satisfied.",
  "The scale is data, not a judgment.",
  "You can reset at breakfast, lunch, dinner, or right now.",
  "Healthy momentum begins with one action you can repeat.",
  "Choose foods that leave you energized, satisfied, and clear.",
  "Your appetite is information worth listening to.",
  "Make protein and vegetables easy to reach.",
  "A strong morning routine can make healthy choices easier all day.",
  "You are building a body you can live well in.",
  "Sustainable progress usually feels less dramatic than crash diets.",
  "Your healthiest self is built through ordinary days.",
  "A ten-minute walk is better than waiting for the perfect workout.",
  "Eat for your goals without forgetting to enjoy the meal.",
  "Healthy boundaries with food can still include flexibility.",
  "Do not confuse hunger with failure; nourish your body wisely.",
  "Let your habits carry you when motivation is absent.",
  "Your health journey should make life bigger, not smaller.",
  "A consistent bedtime can support goals more than another late workout.",
  "Drink before you are thirsty when the day gets busy.",
  "Choose meals that satisfy you enough to stay consistent.",
  "Slow progress is still progress you can keep.",
  "Health grows from what you repeat, not what you do once.",
  "You can be disciplined without being harsh with yourself.",
  "Your next meal is always a fresh opportunity.",
  "Keep healthy food convenient and good decisions become easier.",
  "A balanced plate is a quiet form of self-care.",
  "Your body needs recovery as much as it needs effort.",
  "Make movement something you look forward to.",
  "You are not starting over; you are continuing with more experience.",
  "Healthy living is a collection of small, repeatable wins.",
  "Choose consistency that survives weekends, holidays, and busy days.",
  "Good habits should feel supportive, not fragile.",
  "If today feels hard, make the next choice simple.",
  "The best calorie target is one you can follow without losing yourself.",
  "Your energy, sleep, mood, and strength matter too.",
  "Eat enough protein to support the work your body does.",
  "Fiber, water, and movement are simple allies for everyday health.",
  "You do not need a new plan every Monday; keep refining the one you have.",
  "Healthy progress happens when good choices become normal choices.",
  "Stay patient with the process and curious about what works for you.",
  "The healthiest choice is often the one you can repeat tomorrow.",
  "Take care of your body before it has to demand your attention.",
  "Build meals around nourishment, then make room for enjoyment.",
  "A healthy life can include dessert, rest days, and celebration.",
  "Your goals should challenge you without exhausting you.",
  "Keep walking. Keep drinking water. Keep choosing again.",
  "The body you want is supported by the habits you keep.",
  "Healthy eating is easier when your environment supports it.",
  "Preparation turns good intentions into easier decisions.",
  "Your metabolism is not a reason to give up on consistency.",
  "Choose patience when quick results tempt you toward extremes.",
  "A nourishing meal is productive, even when nothing else gets done.",
  "Eat to feel capable, focused, and strong.",
  "The best progress often comes from doing less, more consistently.",
  "One healthy week is good; a healthy rhythm is better.",
  "Be the person who returns to the plan without drama.",
  "Your body is listening to your habits more than your intentions.",
  "Use tracking as a guide, not a cage.",
  "A flexible plan can be stronger than a strict one.",
  "Healthy living should leave space for people, joy, and memories.",
  "You deserve goals that improve both your health and your life.",
  "Every day you practice, healthy choices become more familiar.",
  "Choose a meal that your body will thank you for later.",
  "Focus on what you can add: protein, plants, water, movement, sleep.",
  "Your routine is your real transformation tool.",
  "Keep your promises small enough to keep and strong enough to matter.",
  "The journey works when you keep coming back to the basics.",
  "Healthy change is easier when you stop rushing it.",
  "Make today's choices kind to tomorrow's body.",
  "You can enjoy the process and still take your goals seriously.",
  "A healthy lifestyle is built to survive imperfect days.",
  "Choose habits that make you feel more alive, not more restricted.",
  "Your strongest progress may be the habits nobody else can see.",
  "Keep going long enough for consistency to become your advantage.",
  "The finish line matters less than becoming someone who lives well.",
  "Today, choose one thing that makes tomorrow healthier.",
] as const;

function jakartaDateKey() {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Jakarta",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
}

function quoteIndex(dateKey: string) {
  let hash = 2166136261;
  for (const char of dateKey) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash) % QUOTES.length;
}

export default function DailyQuote() {
  const quote = QUOTES[quoteIndex(jakartaDateKey())];

  return (
    <div className="daily-quote" aria-label="Daily healthy lifestyle quote">
      <span className="daily-quote-mark" aria-hidden="true">“</span>
      <span>{quote}</span>
    </div>
  );
}
