export const EXTRA_MEME_QUOTES = [
  "If the snack drawer had a loyalty program, you two would be platinum. 🍪💳😂",
  "The fridge light is not a wellness lamp, guys. Close the door. 🧊💡😭",
  "A walk after dinner is cheaper than arguing with your step count. 🚶⌚😂",
  "Your protein goal called. It would like to stop being ignored. 📞🍗",
  "Hydration is not optional DLC. Drink the water. 💧🎮",
  "The couch has enough memories with you two. Go collect some steps. 🛋️🚶",
  "If hunger had push notifications, yours would be permanently enabled. 🍽️📲",
  "Healthy food can taste good. Seasoning was invented for a reason. 🌶️🥗",
  "Your meal plan is not a suggestion box. 😭📋",
  "A balanced meal is basically adulting with garnish. 🍽️✨",
  "Your sleep debt has entered collections. Please go to bed. 😴💸",
  "Going for a walk together is romantic until somebody checks the step count. 🚶❤️⌚",
  "That protein shake cannot undo four hours of sleep, besties. 🥤😴",
  "Water tastes better when you remember headaches are annoying. 💧🤕",
  "Your vegetables would like a speaking role, not a cameo. 🥦🎬",
  "If the workout feels dramatic, lower the volume and do ten minutes. 🎭🏃",
  "Meal prep is boring until hunger starts making executive decisions. 🍱💼",
  "Your body is not asking for perfection. It is asking for lunch. 🍛😂",
  "One donut is dessert. Six donuts is a board meeting. 🍩📊",
  "Steps are steps, even if half of them happened while looking for snacks. 🚶🍿",
  "The scale does not need a daily press conference. ⚖️🎤",
  "Protein at breakfast: because chaos at noon is overrated. 🍳😵",
  "A healthy relationship includes sharing love, not necessarily fries. ❤️🍟😂",
  "The gym did not ghost you. You stopped replying. 🏋️👻",
  "Your water bottle has been carrying this relationship. 💧❤️😂",
  "Eating slowly is free. Somehow we still speedrun lunch. 🍽️🏎️",
  "You do not need a perfect workout playlist to move your legs. 🎧🚶",
  "Healthy habits are basically tiny chores with excellent long-term plot development. 🧹📈",
  "The fruit bowl is not home decor. 🍎🏠😭",
  "If you can remember your phone charger, you can remember your water bottle. 🔌💧",
  "Your bedtime deserves the same respect as your dinner reservation. 😴📅",
  "A salad with flavor is still a salad. Revolutionary, I know. 🥗🌶️",
  "Walking together counts as cardio and gossip management. 🚶🗣️😂",
  "Your muscles are not psychic. Feed them protein. 💪🍗",
  "The weekend did not delete your goals. It just added snacks. 📅🍿",
  "If healthy eating feels like punishment, your recipes need legal representation. 🍲⚖️",
  "You two do not need another diet hack. You need groceries and sleep. 🛒😴",
  "Resting is productive when your body is the project. 🛌📈",
  "A ten-minute workout still beats a sixty-minute argument with yourself. 🏃🧠",
  "Your hunger is not a software bug. Please feed the system. 🍽️💻",
  "The snack was not invisible just because nobody watched you eat it. 🍪👀😂",
  "Hydrate now so future-you can stop being dramatic about headaches. 💧🎭",
  "Meal prep is basically sending edible emails to your future self. 🍱📧",
  "You can have dessert. Just stop acting like dessert signed a hostile takeover. 🍰📈",
  "Your fitness journey does not need cinematic background music every day. 🎬🏃",
  "A short walk is still movement. Nobody is grading the choreography. 🚶💃",
  "Eating vegetables will not make you boring. Your group chat already handles that. 🥦📱😂",
  "The calorie tracker is a tool, not your strict aunt at dinner. 📊🍽️",
  "Your water bottle is literally right there. This is getting embarrassing. 💧👀",
  "Healthy couples lift each other up and occasionally remind each other to eat protein. ❤️💪",
  "Sleep is the original performance-enhancing substance. Legal and free. 😴⚡",
  "That five-minute stretch may prevent tomorrow-you from moving like old furniture. 🧘🪑",
  "Your lunch does not need to be aesthetic. It needs to exist. 🍱📸",
  "A banana is faster than a motivational speech and probably more useful right now. 🍌🎤",
  "If you are hungry, eat. We are doing health, not a survival reality show. 🍽️🏝️",
  "One skipped workout is recovery. Twenty skipped workouts is a new hobby. 😂🏋️",
  "You can order the burger. Maybe let the vegetables attend too. 🍔🥬",
  "The healthiest plan is the one you two do not rage-quit by Thursday. 📅🎮",
  "Drink water before the iced coffee starts believing it is your emergency contact. 💧☕",
  "Your body has enough drama. Give it protein, sleep, water, and fewer plot twists. 🍗😴💧🎬",
] as const;
